version: '3.8'

services:
  web:
    build: ./hse_tpr
    command: gunicorn hse_tpr.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    links:
      - db
    network_mode: bridge
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    network_mode: bridge
    ports:
      - 5434:5432/tcp

volumes:
  postgres_data: