version: '3.8'

services:
  web:
    build: ./hse_tpr
    command: python manage.py runserver 0:8000
    volumes:
      - ./hse_tpr/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    # network_mode: bridge
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=hse_tpr_dev
      - POSTGRES_USER=hse_tpr
      - POSTGRES_PASSWORD=hse_tpr
    ports:
      - 5432:5432/tcp
    # network_mode: bridge

volumes:
  postgres_data: