# Generated by Django 4.2 on 2023-05-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_alter_educationalcase_case_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalcase',
            name='other_information',
            field=models.TextField(blank=True),
        ),
    ]
