name: Django CI

on:
  push:
    branches: [ "prep_prod" ]
  pull_request:
    branches: [ "prep_prod" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Make and apply migrations
      working-directory: ./hse_tpr
      run: |
        python manage.py makemigrations
        python manage.py migrate
    - name: Django Migration Checker
      # You may pin to the exact commit or the version.
      # uses: hardcoretech/django-migration-checker-action@8980b8013dc1722a27c0c852e8dd94c1601d3f5d
      uses: hardcoretech/django-migration-checker-action@v1
      with:
        # app folder path
        app-path: ./hse_tpr/registration
